INSERT INTO scripts (iso, name) VALUES ('Adlm', 'Adlam');
INSERT INTO scripts (iso, name) VALUES ('Afak', 'Afaka');
INSERT INTO scripts (iso, name) VALUES ('Aghb', 'Caucasian Albanian');
INSERT INTO scripts (iso, name) VALUES ('Ahom', 'Ahom');
INSERT INTO scripts (iso, name) VALUES ('Arab', 'Arabic');
INSERT INTO scripts (iso, name) VALUES ('Aran', 'Nastaliq Arabic');
INSERT INTO scripts (iso, name) VALUES ('Armi', 'Imperial Aramaic');
INSERT INTO scripts (iso, name) VALUES ('Armn', 'Armenian');
INSERT INTO scripts (iso, name) VALUES ('Avst', 'Avestan');
INSERT INTO scripts (iso, name) VALUES ('Bali', 'Balinese');
INSERT INTO scripts (iso, name) VALUES ('Bamu', 'Bamum');
INSERT INTO scripts (iso, name) VALUES ('Bass', 'Bassa Vah');
INSERT INTO scripts (iso, name) VALUES ('Batk', 'Batak');
INSERT INTO scripts (iso, name) VALUES ('Beng', 'Bengali');
INSERT INTO scripts (iso, name) VALUES ('Bhks', 'Bhaiksuki');
INSERT INTO scripts (iso, name) VALUES ('Blis', 'Bliss');
INSERT INTO scripts (iso, name) VALUES ('Bopo', 'Bopomofo');
INSERT INTO scripts (iso, name) VALUES ('Brah', 'Brahmi');
INSERT INTO scripts (iso, name) VALUES ('Brai', 'Braille');
INSERT INTO scripts (iso, name) VALUES ('Bugi', 'Buginese');
INSERT INTO scripts (iso, name) VALUES ('Buhd', 'Buhid');
INSERT INTO scripts (iso, name) VALUES ('Cakm', 'Chakma');
INSERT INTO scripts (iso, name) VALUES ('Cans', 'Canadian Aboriginal');
INSERT INTO scripts (iso, name) VALUES ('Cari', 'Carian');
INSERT INTO scripts (iso, name) VALUES ('Cham', 'Cham');
INSERT INTO scripts (iso, name) VALUES ('Cher', 'Cherokee');
INSERT INTO scripts (iso, name) VALUES ('Chrs', 'Chorasmian');
INSERT INTO scripts (iso, name) VALUES ('Cirt', 'Cirth');
INSERT INTO scripts (iso, name) VALUES ('Copt', 'Coptic');
INSERT INTO scripts (iso, name) VALUES ('Cpmn', 'Cypro Minoan');
INSERT INTO scripts (iso, name) VALUES ('Cprt', 'Cypriot');
INSERT INTO scripts (iso, name) VALUES ('Cyrl', 'Cyrillic');
INSERT INTO scripts (iso, name) VALUES ('Cyrs', 'Old Cyrillic');
INSERT INTO scripts (iso, name) VALUES ('Deva', 'Devanagari');
INSERT INTO scripts (iso, name) VALUES ('Diak', 'Dhives Akuru');
INSERT INTO scripts (iso, name) VALUES ('Dogr', 'Dogri');
INSERT INTO scripts (iso, name) VALUES ('Dsrt', 'Deseret');
INSERT INTO scripts (iso, name) VALUES ('Dupl', 'Duployan');
INSERT INTO scripts (iso, name) VALUES ('Egyd', 'Demotic');
INSERT INTO scripts (iso, name) VALUES ('Egyh', 'Hieratic');
INSERT INTO scripts (iso, name) VALUES ('Egyp', 'Egyptian Hieroglyphs');
INSERT INTO scripts (iso, name) VALUES ('Elba', 'Elbasan');
INSERT INTO scripts (iso, name) VALUES ('Elym', 'Elymaic');
INSERT INTO scripts (iso, name) VALUES ('Ethi', 'Ethiopic');
INSERT INTO scripts (iso, name) VALUES ('Gara', 'Garay');
INSERT INTO scripts (iso, name) VALUES ('Geok', 'Chutsuri');
INSERT INTO scripts (iso, name) VALUES ('Geor', 'Georgian');
INSERT INTO scripts (iso, name) VALUES ('Glag', 'Glagolitic');
INSERT INTO scripts (iso, name) VALUES ('Gong', 'Gundjala Gondi');
INSERT INTO scripts (iso, name) VALUES ('Gonm', 'Gondi');
INSERT INTO scripts (iso, name) VALUES ('Goth', 'Gothic');
INSERT INTO scripts (iso, name) VALUES ('Gran', 'Grantha');
INSERT INTO scripts (iso, name) VALUES ('Grek', 'Greek');
INSERT INTO scripts (iso, name) VALUES ('Gujr', 'Gujarati');
INSERT INTO scripts (iso, name) VALUES ('Gukh', 'Gurung Khema');
INSERT INTO scripts (iso, name) VALUES ('Guru', 'Gurmukhi');
INSERT INTO scripts (iso, name) VALUES ('Hanb', 'Han Bopomofo');
INSERT INTO scripts (iso, name) VALUES ('Hang', 'Hangul');
INSERT INTO scripts (iso, name) VALUES ('Hani', 'Han');
INSERT INTO scripts (iso, name) VALUES ('Hano', 'Hanunoo');
INSERT INTO scripts (iso, name) VALUES ('Hans', 'Han Simplified');
INSERT INTO scripts (iso, name) VALUES ('Hant', 'Han Traditional');
INSERT INTO scripts (iso, name) VALUES ('Hatr', 'Hatran');
INSERT INTO scripts (iso, name) VALUES ('Hebr', 'Hebrew');
INSERT INTO scripts (iso, name) VALUES ('Hira', 'Hiragana');
INSERT INTO scripts (iso, name) VALUES ('Hluw', 'Anatolian Hieroglyphs');
INSERT INTO scripts (iso, name) VALUES ('Hmng', 'Pahawh Hmong');
INSERT INTO scripts (iso, name) VALUES ('Hmnp', 'Nyiakeng Puachue Hmong');
INSERT INTO scripts (iso, name) VALUES ('Hrkt', 'Katakana Or Hiragana');
INSERT INTO scripts (iso, name) VALUES ('Hung', 'Old Hungarian');
INSERT INTO scripts (iso, name) VALUES ('Inds', 'Indus');
INSERT INTO scripts (iso, name) VALUES ('Ital', 'Old Italic');
INSERT INTO scripts (iso, name) VALUES ('Java', 'Javanese');
INSERT INTO scripts (iso, name) VALUES ('Jpan', 'Japanese');
INSERT INTO scripts (iso, name) VALUES ('Jurc', 'Jurchen');
INSERT INTO scripts (iso, name) VALUES ('Kali', 'Kayah Li');
INSERT INTO scripts (iso, name) VALUES ('Kana', 'Katakana');
INSERT INTO scripts (iso, name) VALUES ('Kawi', 'Kawi');
INSERT INTO scripts (iso, name) VALUES ('Khar', 'Kharoshthi');
INSERT INTO scripts (iso, name) VALUES ('Khmr', 'Khmer');
INSERT INTO scripts (iso, name) VALUES ('Khoj', 'Khojki');
INSERT INTO scripts (iso, name) VALUES ('Kitl', 'Khitan Large');
INSERT INTO scripts (iso, name) VALUES ('Kits', 'Khitan Small');
INSERT INTO scripts (iso, name) VALUES ('Knda', 'Kannada');
INSERT INTO scripts (iso, name) VALUES ('Kore', 'Korean Mixed');
INSERT INTO scripts (iso, name) VALUES ('Kpel', 'Kpelle');
INSERT INTO scripts (iso, name) VALUES ('Krai', 'Kirat Rai');
INSERT INTO scripts (iso, name) VALUES ('Kthi', 'Kaithi');
INSERT INTO scripts (iso, name) VALUES ('Lana', 'Tai Tham');
INSERT INTO scripts (iso, name) VALUES ('Laoo', 'Lao');
INSERT INTO scripts (iso, name) VALUES ('Latf', 'Latin Fraktur' );
INSERT INTO scripts (iso, name) VALUES ('Latg', 'Latin Gaelic' );
INSERT INTO scripts (iso, name) VALUES ('Latn', 'Latin');
INSERT INTO scripts (iso, name) VALUES ('Leke', 'Leke' );
INSERT INTO scripts (iso, name) VALUES ('Lepc', 'Lepcha');
INSERT INTO scripts (iso, name) VALUES ('Limb', 'Limbu');
INSERT INTO scripts (iso, name) VALUES ('Lina', 'Linear A' );
INSERT INTO scripts (iso, name) VALUES ('Linb', 'Linear B');
INSERT INTO scripts (iso, name) VALUES ('Lisu', 'Lisu');
INSERT INTO scripts (iso, name) VALUES ('Lyci', 'Lycian');
INSERT INTO scripts (iso, name) VALUES ('Lydi', 'Lydian');
INSERT INTO scripts (iso, name) VALUES ('Mahj', 'Mahajani');
INSERT INTO scripts (iso, name) VALUES ('Maka', 'Makasar' );
INSERT INTO scripts (iso, name) VALUES ('Mand', 'Mandaic');
INSERT INTO scripts (iso, name) VALUES ('Mani', 'Manichaean' );
INSERT INTO scripts (iso, name) VALUES ('Marc', 'Marchen' );
INSERT INTO scripts (iso, name) VALUES ('Maya', 'Maya' );
INSERT INTO scripts (iso, name) VALUES ('Medf', 'Medefaidrin' );
INSERT INTO scripts (iso, name) VALUES ('Mend', 'Mende Kikakui' );
INSERT INTO scripts (iso, name) VALUES ('Merc', 'Meroitic Cursive');
INSERT INTO scripts (iso, name) VALUES ('Mero', 'Meroitic Hieroglyphs');
INSERT INTO scripts (iso, name) VALUES ('Mlym', 'Malayalam');
INSERT INTO scripts (iso, name) VALUES ('Modi', 'Modi' );
INSERT INTO scripts (iso, name) VALUES ('Mong', 'Mongolian');
INSERT INTO scripts (iso, name) VALUES ('Moon', 'Moon System' );
INSERT INTO scripts (iso, name) VALUES ('Mroo', 'Mro' );
INSERT INTO scripts (iso, name) VALUES ('Mtei', 'Meetei Mayek');
INSERT INTO scripts (iso, name) VALUES ('Mult', 'Multani');
INSERT INTO scripts (iso, name) VALUES ('Mymr', 'Myanmar');
INSERT INTO scripts (iso, name) VALUES ('Nagm', 'Nag Mundari');
INSERT INTO scripts (iso, name) VALUES ('Nand', 'Nandinagari' );
INSERT INTO scripts (iso, name) VALUES ('Narb', 'Ancient North Arabian' );
INSERT INTO scripts (iso, name) VALUES ('Nbat', 'Nabataean' );
INSERT INTO scripts (iso, name) VALUES ('Newa', 'Prachalit' );
INSERT INTO scripts (iso, name) VALUES ('Nkdb', 'Dongba' );
INSERT INTO scripts (iso, name) VALUES ('Nkgb', 'Geba');
INSERT INTO scripts (iso, name) VALUES ('Nkoo', 'Nko');
INSERT INTO scripts (iso, name) VALUES ('Nshu', 'Nushu' );
INSERT INTO scripts (iso, name) VALUES ('Ogam', 'Ogham');
INSERT INTO scripts (iso, name) VALUES ('Olck', 'Ol Chiki');
INSERT INTO scripts (iso, name) VALUES ('Onao', 'Ol Onal');
INSERT INTO scripts (iso, name) VALUES ('Orkh', 'Old Turkic');
INSERT INTO scripts (iso, name) VALUES ('Orya', 'Oriya');
INSERT INTO scripts (iso, name) VALUES ('Osge', 'Osage' );
INSERT INTO scripts (iso, name) VALUES ('Osma', 'Osmanya');
INSERT INTO scripts (iso, name) VALUES ('Ougr', 'Old Uyghur');
INSERT INTO scripts (iso, name) VALUES ('Palm', 'Palmyrene');
INSERT INTO scripts (iso, name) VALUES ('Pauc', 'Pau Cin Hau');
INSERT INTO scripts (iso, name) VALUES ('Pcun', 'Proto-Cuneiform');
INSERT INTO scripts (iso, name) VALUES ('Pelm', 'Protoelamite');
INSERT INTO scripts (iso, name) VALUES ('Perm', 'Old Permic');
INSERT INTO scripts (iso, name) VALUES ('Phag', 'Phags Pa');
INSERT INTO scripts (iso, name) VALUES ('Phli', 'Inscriptional Pahlavi');
INSERT INTO scripts (iso, name) VALUES ('Phlp', 'Psalter Pahlavi');
INSERT INTO scripts (iso, name) VALUES ('Phlv', 'Book Pahlavi');
INSERT INTO scripts (iso, name) VALUES ('Phnx', 'Phoenician');
INSERT INTO scripts (iso, name) VALUES ('Plrd', 'Miao');
INSERT INTO scripts (iso, name) VALUES ('Prti', 'Inscriptional Parthian');
INSERT INTO scripts (iso, name) VALUES ('Psin', 'Protosinaitic');
INSERT INTO scripts (iso, name) VALUES ('Ranj', 'Ranjana');
INSERT INTO scripts (iso, name) VALUES ('Rjng', 'Rejang');
INSERT INTO scripts (iso, name) VALUES ('Rohg', 'Hanifi Rohingya');
INSERT INTO scripts (iso, name) VALUES ('Roro', 'Rongorongo');
INSERT INTO scripts (iso, name) VALUES ('Runr', 'Runic');
INSERT INTO scripts (iso, name) VALUES ('Samr', 'Samaritan');
INSERT INTO scripts (iso, name) VALUES ('Sara', 'Sarati');
INSERT INTO scripts (iso, name) VALUES ('Sarb', 'Old South Arabian');
INSERT INTO scripts (iso, name) VALUES ('Saur', 'Saurashtra');
INSERT INTO scripts (iso, name) VALUES ('Sgnw', 'Sutton SignWriting');
INSERT INTO scripts (iso, name) VALUES ('Shaw', 'Shavian');
INSERT INTO scripts (iso, name) VALUES ('Shrd', 'Sharada');
INSERT INTO scripts (iso, name) VALUES ('Shui', 'Sui');
INSERT INTO scripts (iso, name) VALUES ('Sidd', 'Siddham');
INSERT INTO scripts (iso, name) VALUES ('Sidt', 'Sidetic');
INSERT INTO scripts (iso, name) VALUES ('Sind', 'Khudabadi');
INSERT INTO scripts (iso, name) VALUES ('Sinh', 'Sinhala');
INSERT INTO scripts (iso, name) VALUES ('Sogd', 'Sogdian');
INSERT INTO scripts (iso, name) VALUES ('Sogo', 'Old Sogdian');
INSERT INTO scripts (iso, name) VALUES ('Sora', 'Sora Sompeng');
INSERT INTO scripts (iso, name) VALUES ('Soyo', 'Soyombo');
INSERT INTO scripts (iso, name) VALUES ('Sund', 'Sundanese');
INSERT INTO scripts (iso, name) VALUES ('Sunu', 'Sunuwar');
INSERT INTO scripts (iso, name) VALUES ('Sylo', 'Syloti Nagri');
INSERT INTO scripts (iso, name) VALUES ('Syrc', 'Syriac');
INSERT INTO scripts (iso, name) VALUES ('Tagb', 'Tagbanwa');
INSERT INTO scripts (iso, name) VALUES ('Takr', 'Takri');
INSERT INTO scripts (iso, name) VALUES ('Tale', 'Tai Le');
INSERT INTO scripts (iso, name) VALUES ('Talu', 'New Tai Lue');
INSERT INTO scripts (iso, name) VALUES ('Taml', 'Tamil');
INSERT INTO scripts (iso, name) VALUES ('Tang', 'Tangut');
INSERT INTO scripts (iso, name) VALUES ('Tavt', 'Tai Viet');
INSERT INTO scripts (iso, name) VALUES ('Tayo', 'Tai Yo');
INSERT INTO scripts (iso, name) VALUES ('Telu', 'Telugu');
INSERT INTO scripts (iso, name) VALUES ('Teng', 'Tengwar');
INSERT INTO scripts (iso, name) VALUES ('Tfng', 'Tifinagh');
INSERT INTO scripts (iso, name) VALUES ('Tglg', 'Tagalog');
INSERT INTO scripts (iso, name) VALUES ('Thaa', 'Thaana');
INSERT INTO scripts (iso, name) VALUES ('Thai', 'Thai');
INSERT INTO scripts (iso, name) VALUES ('Tibt', 'Tibetan');
INSERT INTO scripts (iso, name) VALUES ('Tirh', 'Tirhuta');
INSERT INTO scripts (iso, name) VALUES ('Tnsa', 'Tangsa');
INSERT INTO scripts (iso, name) VALUES ('Todr', 'Todrhi');
INSERT INTO scripts (iso, name) VALUES ('Tols', 'Tolong Siki');
INSERT INTO scripts (iso, name) VALUES ('Toto', 'Toto');
INSERT INTO scripts (iso, name) VALUES ('Tutg', 'Tulu-Tigalari');
INSERT INTO scripts (iso, name) VALUES ('Ugar', 'Ugaritic');
INSERT INTO scripts (iso, name) VALUES ('Vaii', 'Vai');
INSERT INTO scripts (iso, name) VALUES ('Visp', 'Visible Speech');
INSERT INTO scripts (iso, name) VALUES ('Vith', 'Vithkuqi');
INSERT INTO scripts (iso, name) VALUES ('Wara', 'Warang Citi');
INSERT INTO scripts (iso, name) VALUES ('Wcho', 'Wancho');
INSERT INTO scripts (iso, name) VALUES ('Wole', 'Woleai');
INSERT INTO scripts (iso, name) VALUES ('Xpeo', 'Old Persian');
INSERT INTO scripts (iso, name) VALUES ('Xsux', 'Cuneiform');
INSERT INTO scripts (iso, name) VALUES ('Yezi', 'Yezidi');
INSERT INTO scripts (iso, name) VALUES ('Yiii', 'Yi');
INSERT INTO scripts (iso, name) VALUES ('Zanb', 'Zanabazar Square');
INSERT INTO scripts (iso, name) VALUES ('Zinh', 'Inherited');
INSERT INTO scripts (iso, name) VALUES ('Zmth', 'Mathematical Notation');
INSERT INTO scripts (iso, name) VALUES ('Zsye', 'Emoji');
INSERT INTO scripts (iso, name) VALUES ('Zsym', 'Symbol');
INSERT INTO scripts (iso, name) VALUES ('Zyyy', 'Common');
INSERT INTO scripts (iso, name) VALUES ('Zzzz', 'Unknown');
